global:
  scrape_interval: 5s  # Set the default scrape interval to 15 seconds

scrape_configs:
  - job_name: 'nodejs-app' 
    static_configs:
      - targets: ['host.docker.internal:8001', 'localhost:8001']